### ISSUE TITLE
[Setting] Tuist 세팅

### ISSUE THREAD

**Issue by HELLOHIDI** [Heylets-sg/heylets-iOS#3]
## 🛠 Issue
- Tuist 세팅하기

## 📋 To-do
- [x] Tuist 코드 세팅
- [x] Config 파일 세팅
- [x] 써드파티 라이브러리 세팅
