### ISSUE TITLE
[Setting] 모듈 세팅하기

### ISSUE THREAD

**Issue by HELLOHIDI** [Heylets-sg/heylets-iOS#4]
## 🛠 Issue
- 모듈 세팅하기

## 📋 To-do
- [ ] Heylets 모듈 세팅하기
- [ ] RootFeature 모듈 세팅하기
- [ ] Onboarding 모듈 세팅하기
- [ ] TimeTable 모듈 세팅하기
- [ ] MyPage 모듈 세팅하기
- [ ] BaseFeatureDependency 모듈 세팅하기
- [ ] Data 모듈 세팅하기
- [ ] Network 모듈 세팅하기
- [ ] Domain 모듈 세팅하기
- [ ] DSKit 모듈 세팅하기
- [ ] Core 모듈 세팅하기
